### ISSUE TITLE
incompatible with TSM

### ISSUE THREAD

**Issue by vioray** [Vladinator/wow-addon-compactvendor#4]
if the addon is used while TSM is enabled then the vendor window is completely blank, only way to get it working is to disable TSM

**Comment by Vladinator** [comment]
This will be fixed once the v2 branch is merged and released with https://github.com/Vladinator/wow-addon-compactvendor/pull/11

The v2 overhauls how the addon does things and it will no longer affect or be affected by other addons, just like this situation.
