### ISSUE TITLE
Incompatible with TipTac addon

### ISSUE THREAD

**Issue by tsroman** [Vladinator/wow-addon-compactvendor#5]
There are issues with tooltips. When you mouse over some item from list.
Tooltip blink to default position (not modified by TipTac) and back, it happens everyth 1-2 sec or so.

CompactVendor- no issues
TipTac - no issues
CompactVendor & TipTac - blinks

**Comment by Vladinator** [comment]
This issue was resolved a while back, old issue, sorry for late response.
