### ISSUE TITLE
vendors are blank (10.0)

### ISSUE THREAD

**Issue by rml9ty** [Vladinator/wow-addon-compactvendor#7]
dont get any lua errors, but vendors don't sell anything anymore either. it's just... blank.

(btw if "Vlad's Dungeon Journal Loot Spec Icons" is also you. I love you for this. looking fwd to an update as well)

**Comment by FireAllianceNX** [comment]
Turning off Wowhead Looter fixes it for me temporarily, but would be ideal to be able to have both running.

**Comment by Vladinator** [comment]
This will be fixed once the v2 branch is merged and released with https://github.com/Vladinator/wow-addon-compactvendor/pull/11

The v2 overhauls how the addon does things and it will no longer affect or be affected by other addons, just like this situation.
