### ISSUE TITLE
Error with Scrap addon

### ISSUE THREAD

**Issue by gz2k2** [Vladinator/wow-addon-compactvendor#8]
Visual Bug on the "Scrap" Tab at the Vendor:

Scrap addon:
https://www.curseforge.com/wow/addons/scrap

Bugged Screen:
![grafik](https://user-images.githubusercontent.com/77876301/200657191-6eab27fa-959f-4957-b8fe-89a4457a331f.png)

**Comment by Vladinator** [comment]
It's something fixed in the next update.

The list only appears on the first tab as expected.
