### ISSUE TITLE
variable icon/font size?

### ISSUE THREAD

**Issue by xizar** [Vladinator/wow-addon-compactvendor#9]
Can you include an option to change (ideally increase) the font size?

For me personally, even just doubling the height of the icons and allowing the font to grow within that range of what's there now to twice as big would be enough.  (This might lead to issues with exceptionally long item names, but even a truncated name would be better than text that getting too small for me to read without a magnifying glass as I get older.)

**Comment by Voxxel** [comment]
+1 for this. 

Compared to other elements of my UI this font size is too small, I can barely read the lines of vendor stuff. I'd enlarge the height of the lines themselves by a few pixels too.

**Comment by Vladinator** [comment]
I have added UI font size option in the upcoming update.

It's not 100% customizable but it's a start.

The size of the icons or preferences are things I can start to add as options now that this is in place.
